name: Pull Request Workflow
on:
  pull_request:
    branches: [ main, integration ]
jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOCKER_CMD: docker-compose -f docker-compose.ci.yml
      DOCKER_EXEC: docker-compose -f docker-compose.ci.yml run app
    
    steps:
    - name: Setup - Checkout code
      uses: actions/checkout@v1

    - name: Start app and db containers
      run: "${DOCKER_CMD} up -d --build --remove-orphans --force-recreate"

    - name: Typecheck
      run: "${DOCKER_EXEC} npm run typecheck"

    - name: Lint
      run: "${DOCKER_EXEC} npm run lint"

    - name: Debug
      run: "${DOCKER_EXEC} ls /app/node_modules"

    - name: Debug 2
      run: "${DOCKER_EXEC} ls /ap/node_modules/esbuild-register"

    - name: Setup Test DB
      run: "${DOCKER_EXEC} npx prisma migrate deploy && npm run db:seed"

    - name: Unit Tests
      run: "${DOCKER_EXEC} npm run test:unit"

    - name: API Tests
      run: "${DOCKER_EXEC} npm run test:api"

    - name: Stop containers
      if: always()
      run: "${DOCKER_CMD} down"
