on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Environment'
        required: true
        default: 'test'
        type: choice
        options:
        - test
      name:
        description: 'Name of the new consumer'
        required: true
        type: string

jobs:
  generate-consumer:
    name: Generate Consumer
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - run: npm i
    - run: npx prisma generate

    - name: Run script
      run: DATABASE_URL=${{ secrets.DATABASE_URL_TEST }} node --require esbuild-register scripts/generate-consumer.ts --name ${{ inputs.name }}
